name: Lambda Deploy

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment (develop, production)'
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true

jobs:
  build-lambda-image:
    runs-on: ubuntu-latest

    outputs:
      image_uri: ${{ steps.login-ecr.outputs.registry }}/${{ steps.login-ecr.outputs.repository }}:matters-server-${{ github.SHA }}
      matters_env: ${{ inputs.environment == 'develop' && 'development' || 'production' }}

    steps:
      - name: Download deployment package
        uses: actions/download-artifact@v4
        with:
          name: deploy-package-${{ inputs.environment }}
          path: .

      - name: unzip deployment package
        run: |
          unzip deploy.zip
          rm deploy.zip

      # AWS Deployment
      - name: Setup AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR for Lambda
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile.lambda .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: lambda-handlers-image
          IMAGE_TAG: matters-server-${{ github.SHA }}

  deploy-recommendation-authors-cache-ahead:
    needs: build-lambda-image
    runs-on: ubuntu-latest
    steps:
      - name: Update Lambda
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: recommendation-authors-cache-ahead-${{ inputs.environment }}
          template: ./deployment/lambda/recommendation-cache-ahead.yml
          parameter-overrides: mattersEnv=$MATTERS_ENV,imageUri=$IMAGE_URL,lambdaCMD=recommendationAuthorsCacheAhead.handler
        env:
          MATTERS_ENV: ${{ needs.build-lambda-image.outputs.matters_env }}
          IMAGE_URL: ${{ needs.build-lambda-image.outputs.image_uri }}

  deploy-recommendation-tags-cache-ahead:
    needs: build-lambda-image
    runs-on: ubuntu-latest
    steps:
      - name: Update Lambda
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: recommendation-tags-cache-ahead-${{ inputs.environment }}
          template: ./deployment/lambda/recommendation-cache-ahead.yml
          parameter-overrides: mattersEnv=$MATTERS_ENV,imageUri=$IMAGE_URL,lambdaCMD=recommendationTagsCacheAhead.handler
        env:
          MATTERS_ENV: ${{ needs.build-lambda-image.outputs.matters_env }}
          IMAGE_URL: ${{ needs.build-lambda-image.outputs.image_uri }}